# Loading CSV

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use ('ggplot')

%matplotlib inline

In [3]:
!ls /home/dsc/Data/us_dot/traffic/

T100_SEGMENT_ALL_CARRIER_2014.zip  T100_SEGMENT_ALL_CARRIER_2015.zip

In [4]:
!unzip -o /home/dsc/Data/us_dot/traffic/T100_SEGMENT_ALL_CARRIER_2015.zip

Archive:  /home/dsc/Data/us_dot/traffic/T100_SEGMENT_ALL_CARRIER_2015.zip
  inflating: 914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv
  inflating: 914310910_T_T100_SEGMENT_ALL_CARRIER_ReadMe.csv
  inflating: 914310910_T_T100_SEGMENT_ALL_CARRIER_Terms.csv

In [9]:
!pwd

/home/dsc/Repositories/master-data-science-nacho/trabajos_jupiter/ejercicio_clase

In [10]:
filename = '914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv'
df = pd.read_csv(filename)
df.sample(4)

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
133955,62.0,57.0,703950.0,2850.0,2058.0,25.0,0.0,431.0,5302.0,3926.0,...,6,675,1,2015,1,1,1,F,DU,NaN
129738,54.0,51.0,510000.0,2550.0,2305.0,0.0,0.0,849.0,9059.0,7582.0,...,6,675,1,2015,1,3,2,F,DU,NaN
37528,0.0,1.0,1978.0,9.0,2.0,0.0,0.0,265.0,0.0,0.0,...,5,575,1,2015,2,4,1,L,DF,NaN
133554,61.0,57.0,2222200.0,8549.0,7273.0,1183.0,0.0,951.0,9416.0,7770.0,...,6,694,1,2015,1,3,2,F,DU,NaN

# Saving to Excel

In [11]:
df.head(1000).to_excel('excel_out.xls')

In [12]:
!ls

01-numpy_pandas_introduction_blank.ipynb
02-loading_and_saving_data_blank.ipynb
03-merge_concatenate_transform_blank.ipynb
2017-12-15-notebook.ipynb
2017-12-16-notebook.ipynb
914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_ReadMe.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_Terms.csv
excel_out.xls

# Saving to CSV

In [13]:
df.sample(10).to_csv('sample.csv')

# To Sql Database

In [14]:
import sqlite3

conn = sqlite3.connect('example.db')

In [16]:
df.to_sql('traffic', conn, if_exists='replace')

/home/dsc/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [19]:
df2 = pd.read_sql_query('SELECT * FROM traffic where passengers > 10000', conn)
df2

,index,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
0,37,0.0,61.0,5365411.0,18353.0,16933.0,571685.0,0.0,4395.0,0.0,...,6,627,1,2015,1,1,9,F,IF,None
1,42,0.0,61.0,5365411.0,18353.0,16827.0,1274568.0,0.0,4395.0,0.0,...,6,627,1,2015,1,1,9,F,IF,None
2,56,0.0,28.0,3619370.0,14448.0,12556.0,478166.0,0.0,3635.0,0.0,...,8,882,1,2015,1,1,8,F,IF,None
3,58,0.0,31.0,4054899.0,15996.0,13913.0,423487.0,0.0,5670.0,0.0,...,8,882,1,2015,1,1,12,F,IF,None
4,59,0.0,27.0,3470887.0,13836.0,12888.0,413138.0,0.0,4589.0,0.0,...,8,882,1,2015,1,1,10,F,IF,None
5,77,0.0,26.0,3360843.0,13416.0,11229.0,291025.0,0.0,3635.0,0.0,...,8,882,1,2015,1,1,8,F,IF,None
6,80,0.0,31.0,4054899.0,15996.0,13433.0,301981.0,0.0,5670.0,0.0,...,8,882,1,2015,1,1,12,F,IF,None
7,85,0.0,27.0,3479696.0,13880.0,12596.0,303890.0,0.0,4589.0,0.0,...,8,882,1,2015,1,1,10,F,IF,None
8,158,0.0,51.0,2706103.0,17384.0,13517.0,0.0,0.0,2002.0,0.0,...,6,627,1,2015,1,1,5,F,IF,None
9,159,0.0,51.0,2751949.0,17384.0,13746.0,0.0,0.0,2002.0,0.0,...,6,627,1,2015,1,1,5,F,IF,None
10,181,0.0,62.0,9292527.0,20584.0,16739.0,1505486.0,0.0,6504.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
11,186,0.0,62.0,9256991.0,20584.0,19123.0,1847391.0,0.0,6504.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
12,212,0.0,59.0,4517040.0,17818.0,14384.0,309318.0,0.0,4661.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
13,218,0.0,59.0,3829100.0,17818.0,16328.0,82482.0,0.0,4661.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
14,224,0.0,45.0,3564000.0,13230.0,11119.0,638163.0,0.0,4095.0,0.0,...,8,871,1,2015,1,1,9,F,IF,None
15,225,0.0,51.0,4039200.0,14994.0,11012.0,392236.0,0.0,4095.0,0.0,...,8,871,1,2015,1,1,9,F,IF,None
16,737,0.0,53.0,8076130.0,18963.0,14745.0,887352.0,0.0,6799.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
17,748,0.0,31.0,4377303.0,11709.0,11144.0,20671.0,0.0,6469.0,0.0,...,8,819,1,2015,1,1,13,F,IF,None
18,754,0.0,53.0,8076130.0,18920.0,15334.0,1268469.0,0.0,6799.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
19,757,0.0,31.0,4377303.0,11681.0,10018.0,253550.0,0.0,6469.0,0.0,...,8,819,1,2015,1,1,13,F,IF,None
20,841,0.0,59.0,5676154.0,13924.0,12012.0,689084.0,0.0,4884.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
21,851,0.0,59.0,5676154.0,13924.0,11197.0,1103216.0,0.0,4884.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
22,857,0.0,59.0,7295000.0,14750.0,12335.0,715746.0,0.0,4278.0,0.0,...,6,696,1,2015,1,1,9,F,IF,None
23,860,0.0,59.0,7284999.0,14750.0,11325.0,851858.0,0.0,4278.0,0.0,...,6,696,1,2015,1,1,9,F,IF,None
24,876,0.0,86.0,4299948.0,13244.0,10516.0,40388.0,0.0,2204.0,0.0,...,6,614,1,2015,1,1,5,F,IF,None
25,888,0.0,85.0,4249949.0,13090.0,11151.0,61239.0,0.0,2204.0,0.0,...,6,614,1,2015,1,1,5,F,IF,None
26,2693,0.0,79.0,4247498.0,15326.0,13317.0,53409.0,0.0,2319.0,0.0,...,6,699,1,2015,1,1,5,F,IF,None
27,2720,0.0,78.0,4193732.0,15132.0,13928.0,115522.0,0.0,2319.0,0.0,...,6,699,1,2015,1,1,5,F,IF,None
28,3162,0.0,161.0,5292070.0,23987.0,20346.0,21604.0,68029.0,859.0,20796.0,...,6,655,1,2015,1,1,2,F,DU,None
29,3165,0.0,133.0,4372310.0,19816.0,14220.0,13869.0,27915.0,134.0,6605.0,...,6,655,1,2015,1,1,1,F,DU,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5061,146902,505.0,505.0,15797300.0,62450.0,47004.0,101656.0,0.0,102.0,20035.0,...,6,608,1,2015,2,4,1,F,DU,None
5062,146903,505.0,504.0,15769200.0,62392.0,48092.0,30224.0,0.0,102.0,17606.0,...,6,608,1,2015,2,4,1,F,DU,None
5063,146906,521.0,521.0,16285800.0,63538.0,51110.0,25958.0,0.0,102.0,17822.0,...,6,608,1,2015,1,3,1,F,DU,None
5064,146908,522.0,522.0,16314400.0,63611.0,51439.0,98011.0,0.0,102.0,21061.0,...,6,608,1,2015,1,3,1,F,DU,None
5065,146910,525.0,524.0,16386600.0,63537.0,44702.0,92078.0,0.0,102.0,21463.0,...,6,608,1,2015,1,1,1,F,DU,None
5066,146911,526.0,525.0,16411100.0,63590.0,49097.0,30821.0,0.0,102.0,18853.0,...,6,608,1,2015,1,1,1,F,DU,None
5067,146913,535.0,534.0,16690700.0,64497.0,53062.0,57292.0,0.0,163.0,25798.0,...,6,608,1,2015,1,2,1,F,DU,None
5068,146914,538.0,535.0,16727800.0,64735.0,52773.0,74516.0,0.0,163.0,24712.0,...,6,608,1,2015,1,2,1,F,DU,None
5069,146915,540.0,538.0,16820600.0,66329.0,52007.0,73443.0,0.0,163.0,24487.0,...,6,608,1,2015,2,4,1,F,DU,None
5070,146916,540.0,540.0,16886100.0,66610.0,49227.0,82500.0,0.0,163.0,24569.0,...,6,608,1,2015,2,4,1,F,DU,None
5071,146917,563.0,563.0,17612200.0,68584.0,58241.0,82918.0,0.0,163.0,25896.0,...,6,608,1,2015,1,3,1,F,DU,None
5072,146918,565.0,565.0,17672100.0,68765.0,57892.0,92282.0,0.0,163.0,26134.0,...,6,608,1,2015,1,3,1,F,DU,None
5073,146919,581.0,580.0,18142300.0,70285.0,51837.0,82410.0,0.0,163.0,26805.0,...,6,608,1,2015,1,1,1,F,DU,None
5074,146920,586.0,584.0,18261300.0,70702.0,56704.0,63820.0,0.0,163.0,27433.0,...,6,608,1,2015,1,1,1,F,DU,None
5075,146921,613.0,603.0,10733400.0,45828.0,37708.0,19396.0,0.0,129.0,28945.0,...,4,482,1,2015,1,2,1,F,DU,None
5076,146922,613.0,605.0,10769000.0,45980.0,37519.0,11802.0,0.0,129.0,26704.0,...,4,482,1,2015,1,2,1,F,DU,None
5077,146924,668.0,661.0,11765800.0,50236.0,38845.0,15019.0,0.0,129.0,32547.0,...,4,482,1,2015,1,1,1,F,DU,None
5078,146925,674.0,664.0,11819200.0,50464.0,39168.0,15244.0,0.0,129.0,30158.0,...,4,482,1,2015,1,1,1,F,DU,None
5079,146926,732.0,731.0,22832200.0,89768.0,67710.0,149891.0,0.0,100.0,29449.0,...,6,608,1,2015,2,4,1,F,DU,None
5080,146927,732.0,728.0,22741700.0,89409.0,68857.0,89972.0,0.0,100.0,27076.0,...,6,608,1,2015,2,4,1,F,DU,None
5081,146928,741.0,740.0,23118800.0,89280.0,68943.0,78235.0,0.0,100.0,30119.0,...,6,608,1,2015,1,2,1,F,DU,None
5082,146929,742.0,741.0,23148900.0,89348.0,68441.0,130509.0,0.0,100.0,29662.0,...,6,608,1,2015,1,2,1,F,DU,None
5083,146930,743.0,726.0,12922800.0,55176.0,43652.0,19569.0,0.0,129.0,34122.0,...,4,482,1,2015,2,4,1,F,DU,None
5084,146931,745.0,732.0,13029600.0,55632.0,43894.0,13763.0,0.0,129.0,32712.0,...,4,482,1,2015,2,4,1,F,DU,None
5085,146932,752.0,727.0,12940600.0,55252.0,44565.0,17728.0,0.0,129.0,32687.0,...,4,482,1,2015,1,3,1,F,DU,None
5086,146933,753.0,729.0,12976200.0,55404.0,44718.0,19043.0,0.0,129.0,34735.0,...,4,482,1,2015,1,3,1,F,DU,None
5087,146934,771.0,766.0,23919200.0,92783.0,73599.0,81189.0,0.0,100.0,29043.0,...,6,608,1,2015,1,3,1,F,DU,None
5088,146935,772.0,772.0,24101700.0,93441.0,72852.0,142730.0,0.0,100.0,31216.0,...,6,608,1,2015,1,3,1,F,DU,None
5089,146936,820.0,815.0,25438100.0,98355.0,70117.0,143209.0,0.0,100.0,32403.0,...,6,608,1,2015,1,1,1,F,DU,None
5090,146937,822.0,814.0,25423500.0,98382.0,75216.0,82020.0,0.0,100.0,32035.0,...,6,608,1,2015,1,1,1,F,DU,None


# To dictionary and to json

In [24]:
df.sample(5).to_dict()

{'AIRCRAFT_CONFIG': {35997: 2, 82868: 1, 83126: 1, 124460: 1, 135623: 1},
 'AIRCRAFT_GROUP': {35997: 4, 82868: 6, 83126: 6, 124460: 6, 135623: 6},
 'AIRCRAFT_TYPE': {35997: 459,
  82868: 638,
  83126: 631,
  124460: 612,
  135623: 612},
 'AIRLINE_ID': {35997: 20225.0,
  82868: 20366.0,
  83126: 20378.0,
  124460: 19393.0,
  135623: 19393.0},
 'AIR_TIME': {35997: 527.0,
  82868: 394.0,
  83126: 385.0,
  124460: 4077.0,
  135623: 8674.0},
 'CARRIER': {35997: 'KS',
  82868: 'EV',
  83126: 'YV',
  124460: 'WN',
  135623: 'WN'},
 'CARRIER_GROUP': {35997: 1, 82868: 3, 83126: 2, 124460: 3, 135623: 3},
 'CARRIER_GROUP_NEW': {35997: 5.0,
  82868: 3.0,
  83126: 2.0,
  124460: 3.0,
  135623: 3.0},
 'CARRIER_NAME': {35997: 'Peninsula Airways Inc.',
  82868: 'ExpressJet Airlines Inc.',
  83126: 'Mesa Airlines Inc.',
  124460: 'Southwest Airlines Co.',
  135623: 'Southwest Airlines Co.'},
 'CLASS': {35997: 'G', 82868: 'F', 83126: 'F', 124460: 'F', 135623: 'F'},
 'DATA_SOURCE': {35997: 'DU',
  82868: 'DU',
  83126: 'DU',
  124460: 'DU',
  135623: 'DU'},
 'DEPARTURES_PERFORMED': {35997: 3.0,
  82868: 7.0,
  83126: 7.0,
  124460: 42.0,
  135623: 67.0},
 'DEPARTURES_SCHEDULED': {35997: 0.0,
  82868: 7.0,
  83126: 7.0,
  124460: 42.0,
  135623: 68.0},
 'DEST': {35997: 'SNP',
  82868: 'IAD',
  83126: 'IAD',
  124460: 'HOU',
  135623: 'SJC'},
 'DEST_AIRPORT_ID': {35997: 14919,
  82868: 12264,
  83126: 12264,
  124460: 12191,
  135623: 14831},
 'DEST_AIRPORT_SEQ_ID': {35997: 1491902,
  82868: 1226402,
  83126: 1226402,
  124460: 1219102,
  135623: 1483103},
 'DEST_CITY_MARKET_ID': {35997: 34919,
  82868: 30852,
  83126: 30852,
  124460: 31453,
  135623: 32457},
 'DEST_CITY_NAME': {35997: 'St. Paul, AK',
  82868: 'Washington, DC',
  83126: 'Washington, DC',
  124460: 'Houston, TX',
  135623: 'San Jose, CA'},
 'DEST_COUNTRY': {35997: 'US',
  82868: 'US',
  83126: 'US',
  124460: 'US',
  135623: 'US'},
 'DEST_COUNTRY_NAME': {35997: 'United States',
  82868: 'United States',
  83126: 'United States',
  124460: 'United States',
  135623: 'United States'},
 'DEST_STATE_ABR': {35997: 'AK',
  82868: 'VA',
  83126: 'VA',
  124460: 'TX',
  135623: 'CA'},
 'DEST_STATE_FIPS': {35997: 2.0,
  82868: 51.0,
  83126: 51.0,
  124460: 48.0,
  135623: 6.0},
 'DEST_STATE_NM': {35997: 'Alaska',
  82868: 'Virginia',
  83126: 'Virginia',
  124460: 'Texas',
  135623: 'California'},
 'DEST_WAC': {35997: 1, 82868: 38, 83126: 38, 124460: 74, 135623: 91},
 'DISTANCE': {35997: 767.0,
  82868: 383.0,
  83126: 296.0,
  124460: 759.0,
  135623: 948.0},
 'DISTANCE_GROUP': {35997: 2, 82868: 1, 83126: 1, 124460: 2, 135623: 2},
 'FREIGHT': {35997: 1321.0,
  82868: 0.0,
  83126: 0.0,
  124460: 11814.0,
  135623: 6912.0},
 'MAIL': {35997: 14194.0, 82868: 0.0, 83126: 0.0, 124460: 0.0, 135623: 0.0},
 'MONTH': {35997: 4, 82868: 3, 83126: 3, 124460: 4, 135623: 1},
 'ORIGIN': {35997: 'ANC',
  82868: 'DTW',
  83126: 'SYR',
  124460: 'ABQ',
  135623: 'DEN'},
 'ORIGIN_AIRPORT_ID': {35997: 10299,
  82868: 11433,
  83126: 15096,
  124460: 10140,
  135623: 11292},
 'ORIGIN_AIRPORT_SEQ_ID': {35997: 1029904,
  82868: 1143302,
  83126: 1509602,
  124460: 1014003,
  135623: 1129202},
 'ORIGIN_CITY_MARKET_ID': {35997: 30299,
  82868: 31295,
  83126: 35096,
  124460: 30140,
  135623: 30325},
 'ORIGIN_CITY_NAME': {35997: 'Anchorage, AK',
  82868: 'Detroit, MI',
  83126: 'Syracuse, NY',
  124460: 'Albuquerque, NM',
  135623: 'Denver, CO'},
 'ORIGIN_COUNTRY': {35997: 'US',
  82868: 'US',
  83126: 'US',
  124460: 'US',
  135623: 'US'},
 'ORIGIN_COUNTRY_NAME': {35997: 'United States',
  82868: 'United States',
  83126: 'United States',
  124460: 'United States',
  135623: 'United States'},
 'ORIGIN_STATE_ABR': {35997: 'AK',
  82868: 'MI',
  83126: 'NY',
  124460: 'NM',
  135623: 'CO'},
 'ORIGIN_STATE_FIPS': {35997: 2.0,
  82868: 26.0,
  83126: 36.0,
  124460: 35.0,
  135623: 8.0},
 'ORIGIN_STATE_NM': {35997: 'Alaska',
  82868: 'Michigan',
  83126: 'New York',
  124460: 'New Mexico',
  135623: 'Colorado'},
 'ORIGIN_WAC': {35997: 1, 82868: 43, 83126: 22, 124460: 86, 135623: 82},
 'PASSENGERS': {35997: 0.0,
  82868: 354.0,
  83126: 425.0,
  124460: 4769.0,
  135623: 7702.0},
 'PAYLOAD': {35997: 22497.0,
  82868: 117280.0,
  83126: 129500.0,
  124460: 1453200.0,
  135623: 2318200.0},
 'QUARTER': {35997: 2, 82868: 1, 83126: 1, 124460: 2, 135623: 1},
 'RAMP_TO_RAMP': {35997: 559.0,
  82868: 540.0,
  83126: 656.0,
  124460: 4739.0,
  135623: 10175.0},
 'REGION': {35997: 'D', 82868: 'D', 83126: 'D', 124460: 'D', 135623: 'D'},
 'SEATS': {35997: 0.0,
  82868: 532.0,
  83126: 490.0,
  124460: 6006.0,
  135623: 9581.0},
 'UNIQUE_CARRIER': {35997: 'KS',
  82868: 'EV',
  83126: 'YV',
  124460: 'WN',
  135623: 'WN'},
 'UNIQUE_CARRIER_ENTITY': {35997: '06975',
  82868: '06085',
  83126: '06689',
  124460: '06725',
  135623: '06725'},
 'UNIQUE_CARRIER_NAME': {35997: 'Peninsula Airways Inc.',
  82868: 'ExpressJet Airlines Inc.',
  83126: 'Mesa Airlines Inc.',
  124460: 'Southwest Airlines Co.',
  135623: 'Southwest Airlines Co.'},
 'Unnamed: 50': {35997: nan, 82868: nan, 83126: nan, 124460: nan, 135623: nan},
 'YEAR': {35997: 2015, 82868: 2015, 83126: 2015, 124460: 2015, 135623: 2015}}

In [26]:
df.sample(5).to_json()

'{"DEPARTURES_SCHEDULED":{"21484":0.0,"12547":0.0,"19476":0.0,"82233":7.0,"126665":48.0},"DEPARTURES_PERFORMED":{"21484":1.0,"12547":1.0,"19476":13.0,"82233":7.0,"126665":50.0},"PAYLOAD":{"21484":1850.0,"12547":12500.0,"19476":1251582.0,"82233":962854.0,"126665":225000.0},"SEATS":{"21484":6.0,"12547":50.0,"19476":3166.0,"82233":0.0,"126665":950.0},"PASSENGERS":{"21484":0.0,"12547":21.0,"19476":2739.0,"82233":0.0,"126665":264.0},"FREIGHT":{"21484":11.0,"12547":0.0,"19476":467012.0,"82233":612024.0,"126665":0.0},"MAIL":{"21484":207.0,"12547":0.0,"19476":0.0,"82233":0.0,"126665":0.0},"DISTANCE":{"21484":28.0,"12547":930.0,"19476":3697.0,"82233":332.0,"126665":150.0},"RAMP_TO_RAMP":{"21484":16.0,"12547":181.0,"19476":0.0,"82233":500.0,"126665":2730.0},"AIR_TIME":{"21484":14.0,"12547":146.0,"19476":0.0,"82233":336.0,"126665":1852.0},"UNIQUE_CARRIER":{"21484":"K3","12547":"9E","19476":"SK","82233":"FX","126665":"ZK"},"AIRLINE_ID":{"21484":20383.0,"12547":20363.0,"19476":19571.0,"82233":20107.0,"126665":20358.0},"UNIQUE_CARRIER_NAME":{"21484":"Venture Travel LLC d\\/b\\/a Taquan Air Service","12547":"Endeavor Air Inc.","19476":"Scandinavian Airlines Sys.","82233":"Federal Express Corporation","126665":"Great Lakes Airlines"},"UNIQUE_CARRIER_ENTITY":{"21484":"06968","12547":"07024","19476":"9484B","82233":"06200","126665":"06932"},"REGION":{"21484":"D","12547":"D","19476":"I","82233":"D","126665":"D"},"CARRIER":{"21484":"K3","12547":"9E","19476":"SK","82233":"FX","126665":"ZK"},"CARRIER_NAME":{"21484":"Venture Travel LLC d\\/b\\/a Taquan Air Service","12547":"Endeavor Air Inc.","19476":"Scandinavian Airlines Sys.","82233":"Federal Express Corporation","126665":"Great Lakes Airlines"},"CARRIER_GROUP":{"21484":1,"12547":2,"19476":0,"82233":3,"126665":1},"CARRIER_GROUP_NEW":{"21484":5.0,"12547":2.0,"19476":0.0,"82233":3.0,"126665":6.0},"ORIGIN_AIRPORT_ID":{"21484":12815,"12547":11057,"19476":13952,"82233":13244,"126665":11292},"ORIGIN_AIRPORT_SEQ_ID":{"21484":1281501,"12547":1105703,"19476":1395201,"82233":1324402,"126665":1129202},"ORIGIN_CITY_MARKET_ID":{"21484":32815,"12547":31057,"19476":31647,"82233":33244,"126665":30325},"ORIGIN":{"21484":"KTB","12547":"CLT","19476":"OSL","82233":"MEM","126665":"DEN"},"ORIGIN_CITY_NAME":{"21484":"Thorne Bay, AK","12547":"Charlotte, NC","19476":"Oslo, Norway","82233":"Memphis, TN","126665":"Denver, CO"},"ORIGIN_STATE_ABR":{"21484":"AK","12547":"NC","19476":null,"82233":"TN","126665":"CO"},"ORIGIN_STATE_FIPS":{"21484":2.0,"12547":37.0,"19476":null,"82233":47.0,"126665":8.0},"ORIGIN_STATE_NM":{"21484":"Alaska","12547":"North Carolina","19476":null,"82233":"Tennessee","126665":"Colorado"},"ORIGIN_COUNTRY":{"21484":"US","12547":"US","19476":"NO","82233":"US","126665":"US"},"ORIGIN_COUNTRY_NAME":{"21484":"United States","12547":"United States","19476":"Norway","82233":"United States","126665":"United States"},"ORIGIN_WAC":{"21484":1,"12547":36,"19476":465,"82233":54,"126665":82},"DEST_AIRPORT_ID":{"21484":12633,"12547":13487,"19476":11618,"82233":10397,"126665":10558},"DEST_AIRPORT_SEQ_ID":{"21484":1263301,"12547":1348702,"19476":1161802,"82233":1039705,"126665":1055803},"DEST_CITY_MARKET_ID":{"21484":32633,"12547":31650,"19476":31703,"82233":30397,"126665":30558},"DEST":{"21484":"KCC","12547":"MSP","19476":"EWR","82233":"ATL","126665":"BFF"},"DEST_CITY_NAME":{"21484":"Coffman Cove, AK","12547":"Minneapolis, MN","19476":"Newark, NJ","82233":"Atlanta, GA","126665":"Scottsbluff, NE"},"DEST_STATE_ABR":{"21484":"AK","12547":"MN","19476":"NJ","82233":"GA","126665":"NE"},"DEST_STATE_FIPS":{"21484":2.0,"12547":27.0,"19476":34.0,"82233":13.0,"126665":31.0},"DEST_STATE_NM":{"21484":"Alaska","12547":"Minnesota","19476":"New Jersey","82233":"Georgia","126665":"Nebraska"},"DEST_COUNTRY":{"21484":"US","12547":"US","19476":"US","82233":"US","126665":"US"},"DEST_COUNTRY_NAME":{"21484":"United States","12547":"United States","19476":"United States","82233":"United States","126665":"United States"},"DEST_WAC":{"21484":1,"12547":63,"19476":21,"82233":34,"126665":65},"AIRCRAFT_GROUP":{"21484":0,"12547":6,"19476":8,"82233":7,"126665":4},"AIRCRAFT_TYPE":{"21484":40,"12547":629,"19476":873,"82233":730,"126665":405},"AIRCRAFT_CONFIG":{"21484":4,"12547":1,"19476":1,"82233":2,"126665":1},"YEAR":{"21484":2015,"12547":2015,"19476":2015,"82233":2015,"126665":2015},"QUARTER":{"21484":1,"12547":1,"19476":1,"82233":1,"126665":1},"MONTH":{"21484":3,"12547":2,"19476":3,"82233":1,"126665":2},"DISTANCE_GROUP":{"21484":1,"12547":2,"19476":8,"82233":1,"126665":1},"CLASS":{"21484":"F","12547":"F","19476":"F","82233":"G","126665":"F"},"DATA_SOURCE":{"21484":"DU","12547":"DU","19476":"IF","82233":"DU","126665":"DU"},"Unnamed: 50":{"21484":null,"12547":null,"19476":null,"82233":null,"126665":null}}'

# Reading Excel

In [29]:
accidentes_2009 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',skiprows=7,skipfooter=1,parse_cols='A:K')
accidentes_2009

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
0,ARGANZUELA,389,54,126,75,9.0,43,9,4.0,5,8
1,BARAJAS,89,6,53,21,NaN,12,2,1.0,2,2
2,CARABANCHEL,375,44,171,137,8.0,36,13,6.0,9,8
3,CENTRO,514,55,171,143,NaN,61,12,3.0,10,12
4,CHAMARTIN,494,70,133,92,10.0,72,22,2.0,6,7
5,CHAMBERI,414,35,87,87,3.0,51,12,4.0,4,5
6,CIUDAD LINEAL,398,64,124,101,3.0,57,17,5.0,4,4
7,FUENCARRAL-EL PARDO,321,47,151,78,11.0,34,16,7.0,2,8
8,HORTALEZA,215,16,109,58,3.0,29,13,7.0,4,4
9,LATINA,298,40,134,85,7.0,24,10,2.0,9,11
10,MONCLOA-ARAVACA,340,57,210,71,11.0,48,8,7.0,1,13
11,MORATALAZ,151,26,59,40,NaN,23,3,2.0,3,4
12,PUENTE DE VALLECAS,367,54,196,122,8.0,22,14,2.0,5,11
13,RETIRO,369,59,74,51,4.0,48,10,8.0,6,6
14,SALAMANCA,535,56,122,104,3.0,107,31,NaN,5,2
15,SAN BLAS,301,29,88,66,3.0,20,10,3.0,2,5
16,TETUAN,338,23,115,101,1.0,42,15,5.0,7,8
17,USERA,214,24,96,53,1.0,13,2,1.0,4,3
18,VICALVARO,86,6,39,15,6.0,9,4,3.0,2,2
19,VILLA DE VALLECAS,142,6,67,36,3.0,8,4,1.0,2,3
20,VILLAVERDE,148,19,65,46,4.0,9,4,3.0,1,8

In [30]:
accidentes_2010 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2010')
accidentes_2010

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
0,ARGANZUELA,403,48,103,75,7,26,15.0,2.0,5.0,6.0
1,BARAJAS,62,5,34,22,1,11,NaN,NaN,NaN,NaN
2,CARABANCHEL,357,35,133,114,7,22,14.0,6.0,7.0,1.0
3,CENTRO,546,43,142,169,2,60,14.0,9.0,13.0,9.0
4,CHAMARTIN,460,67,128,85,11,77,16.0,1.0,8.0,5.0
5,CHAMBERI,361,34,86,103,1,66,14.0,5.0,2.0,4.0
6,CIUDAD LINEAL,404,79,120,90,8,39,12.0,6.0,7.0,2.0
7,FUENCARRAL-EL PARDO,294,49,165,72,10,26,9.0,6.0,3.0,2.0
8,HORTALEZA,183,15,68,44,4,11,8.0,4.0,3.0,3.0
9,LATINA,273,37,93,94,6,24,4.0,7.0,10.0,4.0
10,MONCLOA-ARAVACA,350,47,177,75,10,45,9.0,6.0,9.0,11.0
11,MORATALAZ,127,21,58,33,6,13,5.0,2.0,2.0,1.0
12,PUENTE DE VALLECAS,324,44,157,107,7,20,9.0,3.0,8.0,7.0
13,RETIRO,349,55,33,57,2,45,12.0,7.0,7.0,5.0
14,SALAMANCA,506,44,131,89,6,89,19.0,1.0,9.0,6.0
15,SAN BLAS,274,27,62,66,2,22,6.0,2.0,5.0,2.0
16,TETUAN,331,25,87,89,3,47,13.0,6.0,4.0,3.0
17,USERA,178,36,78,78,4,14,2.0,4.0,NaN,4.0
18,VICALVARO,65,4,60,22,3,16,NaN,1.0,1.0,5.0
19,VILLA DE VALLECAS,124,9,63,32,8,9,3.0,1.0,NaN,3.0
20,VILLAVERDE,147,21,58,54,2,9,4.0,2.0,2.0,1.0

In [57]:
accidentes_2009 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2009')
accidentes_2009['YEAR']= '2009'

accidentes_2010 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2010')
accidentes_2010['YEAR']= '2010'

accidentes_2011 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2011')
accidentes_2011['YEAR']= '2011'

accidentes_totales = pd.concat([accidentes_2009, accidentes_2010, accidentes_2011], ignore_index=True)
accidentes_totales.sort_values(by=['DISTRITO_ACCIDENTE'])
#accidentes_totales[['DISTRITO_ACCIDENTE', 'YEAR', ]]

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,YEAR
0,ARGANZUELA,389,54,126,75,9.0,43,9.0,4.0,5.0,8.0,2009
21,ARGANZUELA,403,48,103,75,7.0,26,15.0,2.0,5.0,6.0,2010
42,ARGANZUELA,373,48,102,61,3.0,45,14.0,5.0,3.0,NaN,2011
1,BARAJAS,89,6,53,21,NaN,12,2.0,1.0,2.0,2.0,2009
22,BARAJAS,62,5,34,22,1.0,11,NaN,NaN,NaN,NaN,2010
43,BARAJAS,78,3,44,30,3.0,9,3.0,NaN,1.0,NaN,2011
2,CARABANCHEL,375,44,171,137,8.0,36,13.0,6.0,9.0,8.0,2009
23,CARABANCHEL,357,35,133,114,7.0,22,14.0,6.0,7.0,1.0,2010
44,CARABANCHEL,381,48,125,103,3.0,36,8.0,10.0,8.0,4.0,2011
3,CENTRO,514,55,171,143,NaN,61,12.0,3.0,10.0,12.0,2009
24,CENTRO,546,43,142,169,2.0,60,14.0,9.0,13.0,9.0,2010
45,CENTRO,528,48,173,149,4.0,77,13.0,6.0,3.0,6.0,2011
4,CHAMARTIN,494,70,133,92,10.0,72,22.0,2.0,6.0,7.0,2009
25,CHAMARTIN,460,67,128,85,11.0,77,16.0,1.0,8.0,5.0,2010
46,CHAMARTIN,514,72,122,73,5.0,76,8.0,7.0,5.0,6.0,2011
26,CHAMBERI,361,34,86,103,1.0,66,14.0,5.0,2.0,4.0,2010
47,CHAMBERI,414,24,72,102,NaN,68,15.0,6.0,7.0,4.0,2011
5,CHAMBERI,414,35,87,87,3.0,51,12.0,4.0,4.0,5.0,2009
48,CIUDAD LINEAL,371,68,150,112,8.0,54,11.0,5.0,6.0,2.0,2011
6,CIUDAD LINEAL,398,64,124,101,3.0,57,17.0,5.0,4.0,4.0,2009
27,CIUDAD LINEAL,404,79,120,90,8.0,39,12.0,6.0,7.0,2.0,2010
49,FUENCARRAL-EL PARDO,312,42,128,89,12.0,30,9.0,16.0,1.0,4.0,2011
7,FUENCARRAL-EL PARDO,321,47,151,78,11.0,34,16.0,7.0,2.0,8.0,2009
28,FUENCARRAL-EL PARDO,294,49,165,72,10.0,26,9.0,6.0,3.0,2.0,2010
50,HORTALEZA,189,18,91,43,3.0,28,12.0,3.0,2.0,2.0,2011
8,HORTALEZA,215,16,109,58,3.0,29,13.0,7.0,4.0,4.0,2009
29,HORTALEZA,183,15,68,44,4.0,11,8.0,4.0,3.0,3.0,2010
51,LATINA,285,35,114,88,1.0,20,8.0,4.0,9.0,3.0,2011
9,LATINA,298,40,134,85,7.0,24,10.0,2.0,9.0,11.0,2009
30,LATINA,273,37,93,94,6.0,24,4.0,7.0,10.0,4.0,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
32,MORATALAZ,127,21,58,33,6.0,13,5.0,2.0,2.0,1.0,2010
53,MORATALAZ,137,16,52,34,5.0,12,6.0,2.0,2.0,3.0,2011
11,MORATALAZ,151,26,59,40,NaN,23,3.0,2.0,3.0,4.0,2009
33,PUENTE DE VALLECAS,324,44,157,107,7.0,20,9.0,3.0,8.0,7.0,2010
54,PUENTE DE VALLECAS,344,54,182,116,4.0,30,14.0,3.0,1.0,4.0,2011
12,PUENTE DE VALLECAS,367,54,196,122,8.0,22,14.0,2.0,5.0,11.0,2009
34,RETIRO,349,55,33,57,2.0,45,12.0,7.0,7.0,5.0,2010
55,RETIRO,367,73,71,68,3.0,50,9.0,6.0,6.0,5.0,2011
13,RETIRO,369,59,74,51,4.0,48,10.0,8.0,6.0,6.0,2009
35,SALAMANCA,506,44,131,89,6.0,89,19.0,1.0,9.0,6.0,2010
56,SALAMANCA,528,69,132,97,1.0,82,17.0,5.0,3.0,6.0,2011
14,SALAMANCA,535,56,122,104,3.0,107,31.0,NaN,5.0,2.0,2009
57,SAN BLAS,285,25,74,71,2.0,32,8.0,5.0,2.0,1.0,2011
15,SAN BLAS,301,29,88,66,3.0,20,10.0,3.0,2.0,5.0,2009
36,SAN BLAS,274,27,62,66,2.0,22,6.0,2.0,5.0,2.0,2010
37,TETUAN,331,25,87,89,3.0,47,13.0,6.0,4.0,3.0,2010
58,TETUAN,321,23,76,87,NaN,60,15.0,4.0,2.0,1.0,2011
16,TETUAN,338,23,115,101,1.0,42,15.0,5.0,7.0,8.0,2009
17,USERA,214,24,96,53,1.0,13,2.0,1.0,4.0,3.0,2009
38,USERA,178,36,78,78,4.0,14,2.0,4.0,NaN,4.0,2010
59,USERA,179,25,67,75,3.0,14,1.0,NaN,4.0,1.0,2011
18,VICALVARO,86,6,39,15,6.0,9,4.0,3.0,2.0,2.0,2009
39,VICALVARO,65,4,60,22,3.0,16,NaN,1.0,1.0,5.0,2010
60,VICALVARO,73,9,43,22,2.0,10,1.0,1.0,2.0,4.0,2011
61,VILLA DE VALLECAS,129,8,44,34,4.0,11,3.0,2.0,1.0,1.0,2011
19,VILLA DE VALLECAS,142,6,67,36,3.0,8,4.0,1.0,2.0,3.0,2009
40,VILLA DE VALLECAS,124,9,63,32,8.0,9,3.0,1.0,NaN,3.0,2010
20,VILLAVERDE,148,19,65,46,4.0,9,4.0,3.0,1.0,8.0,2009
41,VILLAVERDE,147,21,58,54,2.0,9,4.0,2.0,2.0,1.0,2010
62,VILLAVERDE,140,10,75,46,1.0,5,5.0,1.0,3.0,2.0,2011

In [ ]:
periodo = [2009,2010,2011,2012,2013,2014,2015]

pd

for i in periodo


accidentes_2009 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2009')
accidentes_2009['YEAR']= '2009'

accidentes_2010 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2010')
accidentes_2010['YEAR']= '2010'

accidentes_2011 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2011')
accidentes_2011['YEAR']= '2011'

accidentes_totales = pd.concat([accidentes_2009, accidentes_2010, accidentes_2011], ignore_index=True)
accidentes_totales.sort_values(by=['DISTRITO_ACCIDENTE'])

In [70]:
sheets= pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname=None)
sheets.keys()
result = []
for name in  sheets.keys():
    year = int(name)
    skiprows = 4 if year==2013 else 7
    this_sheet = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=skiprows,skipfooter=1,parse_cols='A:K',sheetname=name)
   
    this_sheet['YEAR']= year
    result.append(this_sheet)
    
whole_df = pd.concat(result)
whole_df.sample(4)

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,YEAR
8,HORTALEZA,215,16,109,58,3.0,29,13.0,7.0,4.0,4.0,2009
10,MONCLOA-ARAVACA,304,50,178,49,7.0,49,8.0,25.0,3.0,4.0,2014
13,RETIRO,349,55,33,57,2.0,45,12.0,7.0,7.0,5.0,2010
17,USERA,204,28,70,59,2.0,13,5.0,1.0,3.0,2.0,2013

In [37]:
type(accidentes_2009)

pandas.core.frame.DataFrame

#### Exercise

Consolidate the excel into one DataFrame: you will need to create a 'YEAR' column. Think how you can iterate through all the DataFrames. Think also where you can take the value of 'YEAR' from.

# Reading mysql database