# Loading CSV

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use ('ggplot')

%matplotlib inline

In [2]:
!ls /home/dsc/Data/us_dot/traffic/

T100_SEGMENT_ALL_CARRIER_2014.zip  T100_SEGMENT_ALL_CARRIER_2015.zip

In [3]:
man unzip

In [4]:
!unzip

UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
  -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
  -I CHARSET  specify a character encoding for UNIX and other archives

See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

In [5]:
!unzip -o

UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
  -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
  -I CHARSET  specify a character encoding for UNIX and other archives

See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer

In [6]:
!unzip -o /home/dsc/Data/us_dot/traffic/T100_SEGMENT_ALL_CARRIER_2015.zip

Archive:  /home/dsc/Data/us_dot/traffic/T100_SEGMENT_ALL_CARRIER_2015.zip
  inflating: 914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv
  inflating: 914310910_T_T100_SEGMENT_ALL_CARRIER_ReadMe.csv
  inflating: 914310910_T_T100_SEGMENT_ALL_CARRIER_Terms.csv

In [7]:
!pwd

/home/dsc/Repositories/master-data-science-nacho/trabajos_jupiter/ejercicio_clase_Phyton

In [8]:
filename = '914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv'
df = pd.read_csv(filename)
df.sample(4)

,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
35026,0.0,1.0,40170.0,160.0,150.0,551.0,0.0,228.0,53.0,38.0,...,6,614,1,2015,2,4,1,F,DU,NaN
77528,5.0,3.0,118839.0,450.0,348.0,5.0,963.0,1747.0,775.0,711.0,...,6,694,1,2015,1,1,4,F,DU,NaN
57046,1.0,1.0,40400.0,150.0,131.0,3520.0,0.0,47.0,46.0,13.0,...,6,614,1,2015,1,3,1,F,DU,NaN
142290,108.0,107.0,2407500.0,8132.0,7154.0,1066.0,0.0,511.0,10847.0,7730.0,...,6,694,1,2015,2,4,2,F,DU,NaN

# Saving to Excel

In [9]:
df.head(1000).to_excel('excel_out2.xls')

In [6]:
df.head(1000).to_excel('excel_out.xls')

In [7]:
!ls

01-numpy_pandas_introduction_blank.ipynb
02-loading_and_saving_data_blank.ipynb
03-merge_concatenate_transform_blank.ipynb
04-group_by_blank.ipynb
05-visualization_introduction_blank.ipynb
06-intro_to_pandas_practical_blank.ipynb
07-ejercicios_de_repaso_de_pandas_blank.ipynb
07-ejercicios_de_repaso_de_pandas.ipynb
2017-12-15-notebook.ipynb
2017-12-16-notebook.ipynb
914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_ReadMe.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_Terms.csv
D1-numpy_pandas_introduction2.html
D1-numpy_pandas_introduction.ipynb
D2-loading_and_saving_data_blank.ipynb
example.db
excel_out.xls
sample.csv

# Saving to CSV

In [5]:
df.sample(10).to_csv('sample.csv')

In [6]:
df.sample(3).to_csv()

',DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,AIR_TIME,UNIQUE_CARRIER,AIRLINE_ID,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY,REGION,CARRIER,CARRIER_NAME,CARRIER_GROUP,CARRIER_GROUP_NEW,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_COUNTRY,ORIGIN_COUNTRY_NAME,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_COUNTRY,DEST_COUNTRY_NAME,DEST_WAC,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50\n34949,0.0,11.0,328900.0,1209.0,824.0,787.0,0.0,610.0,1202.0,989.0,DL,19790.0,Delta Air Lines Inc.,01260,D,DL,Delta Air Lines Inc.,3,3.0,13244,1324402,33244,MEM,"Memphis, TN",TN,47.0,Tennessee,US,United States,54,11433,1143302,31295,DTW,"Detroit, MI",MI,26.0,Michigan,US,United States,43,6,608,1,2015,2,4,2,F,DU,\n115754,30.0,30.0,534000.0,2280.0,2068.0,316.0,0.0,626.0,3695.0,3028.0,QX,19687.0,Horizon Air,06580,D,QX,Horizon Air,2,2.0,11638,1163805,31638,FAT,"Fresno, CA",CA,6.0,California,US,United States,91,14057,1405702,34057,PDX,"Portland, OR",OR,41.0,Oregon,US,United States,92,4,482,1,2015,2,4,2,F,DU,\n112552,28.0,27.0,1619319.0,6804.0,5048.0,41204.0,101279.0,7919.0,25641.0,24845.0,UA,19977.0,United Air Lines Inc.,10877,P,UA,United Air Lines Inc.,3,3.0,12892,1289203,32575,LAX,"Los Angeles, CA",CA,6.0,California,US,United States,91,13243,1324302,33238,MEL,"Melbourne, Australia",,,,AU,Australia,802,8,889,1,2015,2,4,16,F,IU,\n'

# To Sql Database

In [9]:
import sqlite3

conn = sqlite3.connect('example.db')

In [10]:
df.to_sql('traffic', conn, if_exists='replace')

/home/dsc/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)

In [11]:
df2 = pd.read_sql_query('SELECT * FROM traffic where passengers > 10000', conn)
df2

,index,DEPARTURES_SCHEDULED,DEPARTURES_PERFORMED,PAYLOAD,SEATS,PASSENGERS,FREIGHT,MAIL,DISTANCE,RAMP_TO_RAMP,...,AIRCRAFT_GROUP,AIRCRAFT_TYPE,AIRCRAFT_CONFIG,YEAR,QUARTER,MONTH,DISTANCE_GROUP,CLASS,DATA_SOURCE,Unnamed: 50
0,37,0.0,61.0,5365411.0,18353.0,16933.0,571685.0,0.0,4395.0,0.0,...,6,627,1,2015,1,1,9,F,IF,None
1,42,0.0,61.0,5365411.0,18353.0,16827.0,1274568.0,0.0,4395.0,0.0,...,6,627,1,2015,1,1,9,F,IF,None
2,56,0.0,28.0,3619370.0,14448.0,12556.0,478166.0,0.0,3635.0,0.0,...,8,882,1,2015,1,1,8,F,IF,None
3,58,0.0,31.0,4054899.0,15996.0,13913.0,423487.0,0.0,5670.0,0.0,...,8,882,1,2015,1,1,12,F,IF,None
4,59,0.0,27.0,3470887.0,13836.0,12888.0,413138.0,0.0,4589.0,0.0,...,8,882,1,2015,1,1,10,F,IF,None
5,77,0.0,26.0,3360843.0,13416.0,11229.0,291025.0,0.0,3635.0,0.0,...,8,882,1,2015,1,1,8,F,IF,None
6,80,0.0,31.0,4054899.0,15996.0,13433.0,301981.0,0.0,5670.0,0.0,...,8,882,1,2015,1,1,12,F,IF,None
7,85,0.0,27.0,3479696.0,13880.0,12596.0,303890.0,0.0,4589.0,0.0,...,8,882,1,2015,1,1,10,F,IF,None
8,158,0.0,51.0,2706103.0,17384.0,13517.0,0.0,0.0,2002.0,0.0,...,6,627,1,2015,1,1,5,F,IF,None
9,159,0.0,51.0,2751949.0,17384.0,13746.0,0.0,0.0,2002.0,0.0,...,6,627,1,2015,1,1,5,F,IF,None
10,181,0.0,62.0,9292527.0,20584.0,16739.0,1505486.0,0.0,6504.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
11,186,0.0,62.0,9256991.0,20584.0,19123.0,1847391.0,0.0,6504.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
12,212,0.0,59.0,4517040.0,17818.0,14384.0,309318.0,0.0,4661.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
13,218,0.0,59.0,3829100.0,17818.0,16328.0,82482.0,0.0,4661.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
14,224,0.0,45.0,3564000.0,13230.0,11119.0,638163.0,0.0,4095.0,0.0,...,8,871,1,2015,1,1,9,F,IF,None
15,225,0.0,51.0,4039200.0,14994.0,11012.0,392236.0,0.0,4095.0,0.0,...,8,871,1,2015,1,1,9,F,IF,None
16,737,0.0,53.0,8076130.0,18963.0,14745.0,887352.0,0.0,6799.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
17,748,0.0,31.0,4377303.0,11709.0,11144.0,20671.0,0.0,6469.0,0.0,...,8,819,1,2015,1,1,13,F,IF,None
18,754,0.0,53.0,8076130.0,18920.0,15334.0,1268469.0,0.0,6799.0,0.0,...,6,637,1,2015,1,1,14,F,IF,None
19,757,0.0,31.0,4377303.0,11681.0,10018.0,253550.0,0.0,6469.0,0.0,...,8,819,1,2015,1,1,13,F,IF,None
20,841,0.0,59.0,5676154.0,13924.0,12012.0,689084.0,0.0,4884.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
21,851,0.0,59.0,5676154.0,13924.0,11197.0,1103216.0,0.0,4884.0,0.0,...,6,696,1,2015,1,1,10,F,IF,None
22,857,0.0,59.0,7295000.0,14750.0,12335.0,715746.0,0.0,4278.0,0.0,...,6,696,1,2015,1,1,9,F,IF,None
23,860,0.0,59.0,7284999.0,14750.0,11325.0,851858.0,0.0,4278.0,0.0,...,6,696,1,2015,1,1,9,F,IF,None
24,876,0.0,86.0,4299948.0,13244.0,10516.0,40388.0,0.0,2204.0,0.0,...,6,614,1,2015,1,1,5,F,IF,None
25,888,0.0,85.0,4249949.0,13090.0,11151.0,61239.0,0.0,2204.0,0.0,...,6,614,1,2015,1,1,5,F,IF,None
26,2693,0.0,79.0,4247498.0,15326.0,13317.0,53409.0,0.0,2319.0,0.0,...,6,699,1,2015,1,1,5,F,IF,None
27,2720,0.0,78.0,4193732.0,15132.0,13928.0,115522.0,0.0,2319.0,0.0,...,6,699,1,2015,1,1,5,F,IF,None
28,3162,0.0,161.0,5292070.0,23987.0,20346.0,21604.0,68029.0,859.0,20796.0,...,6,655,1,2015,1,1,2,F,DU,None
29,3165,0.0,133.0,4372310.0,19816.0,14220.0,13869.0,27915.0,134.0,6605.0,...,6,655,1,2015,1,1,1,F,DU,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5061,146902,505.0,505.0,15797300.0,62450.0,47004.0,101656.0,0.0,102.0,20035.0,...,6,608,1,2015,2,4,1,F,DU,None
5062,146903,505.0,504.0,15769200.0,62392.0,48092.0,30224.0,0.0,102.0,17606.0,...,6,608,1,2015,2,4,1,F,DU,None
5063,146906,521.0,521.0,16285800.0,63538.0,51110.0,25958.0,0.0,102.0,17822.0,...,6,608,1,2015,1,3,1,F,DU,None
5064,146908,522.0,522.0,16314400.0,63611.0,51439.0,98011.0,0.0,102.0,21061.0,...,6,608,1,2015,1,3,1,F,DU,None
5065,146910,525.0,524.0,16386600.0,63537.0,44702.0,92078.0,0.0,102.0,21463.0,...,6,608,1,2015,1,1,1,F,DU,None
5066,146911,526.0,525.0,16411100.0,63590.0,49097.0,30821.0,0.0,102.0,18853.0,...,6,608,1,2015,1,1,1,F,DU,None
5067,146913,535.0,534.0,16690700.0,64497.0,53062.0,57292.0,0.0,163.0,25798.0,...,6,608,1,2015,1,2,1,F,DU,None
5068,146914,538.0,535.0,16727800.0,64735.0,52773.0,74516.0,0.0,163.0,24712.0,...,6,608,1,2015,1,2,1,F,DU,None
5069,146915,540.0,538.0,16820600.0,66329.0,52007.0,73443.0,0.0,163.0,24487.0,...,6,608,1,2015,2,4,1,F,DU,None
5070,146916,540.0,540.0,16886100.0,66610.0,49227.0,82500.0,0.0,163.0,24569.0,...,6,608,1,2015,2,4,1,F,DU,None
5071,146917,563.0,563.0,17612200.0,68584.0,58241.0,82918.0,0.0,163.0,25896.0,...,6,608,1,2015,1,3,1,F,DU,None
5072,146918,565.0,565.0,17672100.0,68765.0,57892.0,92282.0,0.0,163.0,26134.0,...,6,608,1,2015,1,3,1,F,DU,None
5073,146919,581.0,580.0,18142300.0,70285.0,51837.0,82410.0,0.0,163.0,26805.0,...,6,608,1,2015,1,1,1,F,DU,None
5074,146920,586.0,584.0,18261300.0,70702.0,56704.0,63820.0,0.0,163.0,27433.0,...,6,608,1,2015,1,1,1,F,DU,None
5075,146921,613.0,603.0,10733400.0,45828.0,37708.0,19396.0,0.0,129.0,28945.0,...,4,482,1,2015,1,2,1,F,DU,None
5076,146922,613.0,605.0,10769000.0,45980.0,37519.0,11802.0,0.0,129.0,26704.0,...,4,482,1,2015,1,2,1,F,DU,None
5077,146924,668.0,661.0,11765800.0,50236.0,38845.0,15019.0,0.0,129.0,32547.0,...,4,482,1,2015,1,1,1,F,DU,None
5078,146925,674.0,664.0,11819200.0,50464.0,39168.0,15244.0,0.0,129.0,30158.0,...,4,482,1,2015,1,1,1,F,DU,None
5079,146926,732.0,731.0,22832200.0,89768.0,67710.0,149891.0,0.0,100.0,29449.0,...,6,608,1,2015,2,4,1,F,DU,None
5080,146927,732.0,728.0,22741700.0,89409.0,68857.0,89972.0,0.0,100.0,27076.0,...,6,608,1,2015,2,4,1,F,DU,None
5081,146928,741.0,740.0,23118800.0,89280.0,68943.0,78235.0,0.0,100.0,30119.0,...,6,608,1,2015,1,2,1,F,DU,None
5082,146929,742.0,741.0,23148900.0,89348.0,68441.0,130509.0,0.0,100.0,29662.0,...,6,608,1,2015,1,2,1,F,DU,None
5083,146930,743.0,726.0,12922800.0,55176.0,43652.0,19569.0,0.0,129.0,34122.0,...,4,482,1,2015,2,4,1,F,DU,None
5084,146931,745.0,732.0,13029600.0,55632.0,43894.0,13763.0,0.0,129.0,32712.0,...,4,482,1,2015,2,4,1,F,DU,None
5085,146932,752.0,727.0,12940600.0,55252.0,44565.0,17728.0,0.0,129.0,32687.0,...,4,482,1,2015,1,3,1,F,DU,None
5086,146933,753.0,729.0,12976200.0,55404.0,44718.0,19043.0,0.0,129.0,34735.0,...,4,482,1,2015,1,3,1,F,DU,None
5087,146934,771.0,766.0,23919200.0,92783.0,73599.0,81189.0,0.0,100.0,29043.0,...,6,608,1,2015,1,3,1,F,DU,None
5088,146935,772.0,772.0,24101700.0,93441.0,72852.0,142730.0,0.0,100.0,31216.0,...,6,608,1,2015,1,3,1,F,DU,None
5089,146936,820.0,815.0,25438100.0,98355.0,70117.0,143209.0,0.0,100.0,32403.0,...,6,608,1,2015,1,1,1,F,DU,None
5090,146937,822.0,814.0,25423500.0,98382.0,75216.0,82020.0,0.0,100.0,32035.0,...,6,608,1,2015,1,1,1,F,DU,None


# To dictionary and to json

In [12]:
df.sample(5).to_dict()

{'AIRCRAFT_CONFIG': {67821: 1, 97533: 2, 127541: 1, 140030: 1, 140443: 1},
 'AIRCRAFT_GROUP': {67821: 6, 97533: 6, 127541: 6, 140030: 6, 140443: 6},
 'AIRCRAFT_TYPE': {67821: 617,
  97533: 692,
  127541: 675,
  140030: 678,
  140443: 655},
 'AIRLINE_ID': {67821: 19930.0,
  97533: 20107.0,
  127541: 20366.0,
  140030: 20409.0,
  140443: 19805.0},
 'AIR_TIME': {67821: 303.0,
  97533: 1223.0,
  127541: 5209.0,
  140030: 7053.0,
  140443: 12716.0},
 'CARRIER': {67821: 'AS',
  97533: 'FX',
  127541: 'EV',
  140030: 'B6',
  140443: 'AA'},
 'CARRIER_GROUP': {67821: 3, 97533: 3, 127541: 3, 140030: 3, 140443: 3},
 'CARRIER_GROUP_NEW': {67821: 3.0,
  97533: 3.0,
  127541: 3.0,
  140030: 3.0,
  140443: 3.0},
 'CARRIER_NAME': {67821: 'Alaska Airlines Inc.',
  97533: 'Federal Express Corporation',
  127541: 'ExpressJet Airlines Inc.',
  140030: 'JetBlue Airways',
  140443: 'American Airlines Inc.'},
 'CLASS': {67821: 'F', 97533: 'G', 127541: 'F', 140030: 'F', 140443: 'F'},
 'DATA_SOURCE': {67821: 'IU',
  97533: 'DU',
  127541: 'DU',
  140030: 'DU',
  140443: 'DU'},
 'DEPARTURES_PERFORMED': {67821: 2.0,
  97533: 18.0,
  127541: 48.0,
  140030: 89.0,
  140443: 90.0},
 'DEPARTURES_SCHEDULED': {67821: 2.0,
  97533: 18.0,
  127541: 50.0,
  140030: 89.0,
  140443: 91.0},
 'DEST': {67821: 'SAN',
  97533: 'OKC',
  127541: 'SDF',
  140030: 'BOS',
  140443: 'AUS'},
 'DEST_AIRPORT_ID': {67821: 14679,
  97533: 13851,
  127541: 14730,
  140030: 10721,
  140443: 10423},
 'DEST_AIRPORT_SEQ_ID': {67821: 1467903,
  97533: 1385103,
  127541: 1473003,
  140030: 1072102,
  140443: 1042302},
 'DEST_CITY_MARKET_ID': {67821: 33570,
  97533: 33851,
  127541: 33044,
  140030: 30721,
  140443: 30423},
 'DEST_CITY_NAME': {67821: 'San Diego, CA',
  97533: 'Oklahoma City, OK',
  127541: 'Louisville, KY',
  140030: 'Boston, MA',
  140443: 'Austin, TX'},
 'DEST_COUNTRY': {67821: 'US',
  97533: 'US',
  127541: 'US',
  140030: 'US',
  140443: 'US'},
 'DEST_COUNTRY_NAME': {67821: 'United States',
  97533: 'United States',
  127541: 'United States',
  140030: 'United States',
  140443: 'United States'},
 'DEST_STATE_ABR': {67821: 'CA',
  97533: 'OK',
  127541: 'KY',
  140030: 'MA',
  140443: 'TX'},
 'DEST_STATE_FIPS': {67821: 6.0,
  97533: 40.0,
  127541: 21.0,
  140030: 25.0,
  140443: 48.0},
 'DEST_STATE_NM': {67821: 'California',
  97533: 'Oklahoma',
  127541: 'Kentucky',
  140030: 'Massachusetts',
  140443: 'Texas'},
 'DEST_WAC': {67821: 91, 97533: 73, 127541: 52, 140030: 13, 140443: 74},
 'DISTANCE': {67821: 1109.0,
  97533: 432.0,
  127541: 788.0,
  140030: 632.0,
  140443: 978.0},
 'DISTANCE_GROUP': {67821: 3, 97533: 1, 127541: 2, 140030: 2, 140443: 2},
 'FREIGHT': {67821: 0.0,
  97533: 896662.0,
  127541: 0.0,
  140030: 289.0,
  140443: 1447.0},
 'MAIL': {67821: 0.0, 97533: 0.0, 127541: 0.0, 140030: 0.0, 140443: 1057.0},
 'MONTH': {67821: 4, 97533: 2, 127541: 2, 140030: 3, 140443: 4},
 'ORIGIN': {67821: 'PVR',
  97533: 'MEM',
  127541: 'IAH',
  140030: 'DTW',
  140443: 'ORD'},
 'ORIGIN_AIRPORT_ID': {67821: 14312,
  97533: 13244,
  127541: 12266,
  140030: 11433,
  140443: 13930},
 'ORIGIN_AIRPORT_SEQ_ID': {67821: 1431202,
  97533: 1324402,
  127541: 1226603,
  140030: 1143302,
  140443: 1393003},
 'ORIGIN_CITY_MARKET_ID': {67821: 34312,
  97533: 33244,
  127541: 31453,
  140030: 31295,
  140443: 30977},
 'ORIGIN_CITY_NAME': {67821: 'Puerto Vallarta, Mexico',
  97533: 'Memphis, TN',
  127541: 'Houston, TX',
  140030: 'Detroit, MI',
  140443: 'Chicago, IL'},
 'ORIGIN_COUNTRY': {67821: 'MX',
  97533: 'US',
  127541: 'US',
  140030: 'US',
  140443: 'US'},
 'ORIGIN_COUNTRY_NAME': {67821: 'Mexico',
  97533: 'United States',
  127541: 'United States',
  140030: 'United States',
  140443: 'United States'},
 'ORIGIN_STATE_ABR': {67821: nan,
  97533: 'TN',
  127541: 'TX',
  140030: 'MI',
  140443: 'IL'},
 'ORIGIN_STATE_FIPS': {67821: nan,
  97533: 47.0,
  127541: 48.0,
  140030: 26.0,
  140443: 17.0},
 'ORIGIN_STATE_NM': {67821: nan,
  97533: 'Tennessee',
  127541: 'Texas',
  140030: 'Michigan',
  140443: 'Illinois'},
 'ORIGIN_WAC': {67821: 148, 97533: 54, 127541: 74, 140030: 43, 140443: 41},
 'PASSENGERS': {67821: 284.0,
  97533: 0.0,
  127541: 1855.0,
  140030: 6894.0,
  140443: 10090.0},
 'PAYLOAD': {67821: 70985.0,
  97533: 1436015.0,
  127541: 480000.0,
  140030: 2331800.0,
  140443: 3354100.0},
 'QUARTER': {67821: 2, 97533: 1, 127541: 1, 140030: 1, 140443: 2},
 'RAMP_TO_RAMP': {67821: 366.0,
  97533: 1582.0,
  127541: 6332.0,
  140030: 8761.0,
  140443: 14969.0},
 'REGION': {67821: 'L', 97533: 'D', 127541: 'D', 140030: 'D', 140443: 'D'},
 'SEATS': {67821: 288.0,
  97533: 0.0,
  127541: 2400.0,
  140030: 8900.0,
  140443: 12600.0},
 'UNIQUE_CARRIER': {67821: 'AS',
  97533: 'FX',
  127541: 'EV',
  140030: 'B6',
  140443: 'AA'},
 'UNIQUE_CARRIER_ENTITY': {67821: '16031',
  97533: '06200',
  127541: '06085',
  140030: '06673',
  140443: '0A050'},
 'UNIQUE_CARRIER_NAME': {67821: 'Alaska Airlines Inc.',
  97533: 'Federal Express Corporation',
  127541: 'ExpressJet Airlines Inc.',
  140030: 'JetBlue Airways',
  140443: 'American Airlines Inc.'},
 'Unnamed: 50': {67821: nan,
  97533: nan,
  127541: nan,
  140030: nan,
  140443: nan},
 'YEAR': {67821: 2015, 97533: 2015, 127541: 2015, 140030: 2015, 140443: 2015}}

In [13]:
df.sample(5).to_json()

'{"DEPARTURES_SCHEDULED":{"18725":0.0,"100471":20.0,"124633":43.0,"26827":0.0,"46188":0.0},"DEPARTURES_PERFORMED":{"18725":1.0,"100471":20.0,"124633":39.0,"26827":1.0,"46188":2.0},"PAYLOAD":{"18725":89270.0,"100471":2148387.0,"124633":744588.0,"26827":6500.0,"46188":69200.0},"SEATS":{"18725":266.0,"100471":0.0,"124633":2691.0,"26827":30.0,"46188":286.0},"PASSENGERS":{"18725":232.0,"100471":0.0,"124633":1492.0,"26827":13.0,"46188":212.0},"FREIGHT":{"18725":670.0,"100471":1170731.0,"124633":0.0,"26827":0.0,"46188":256.0},"MAIL":{"18725":332.0,"100471":82310.0,"124633":0.0,"26827":0.0,"46188":0.0},"DISTANCE":{"18725":3166.0,"100471":1834.0,"124633":660.0,"26827":160.0,"46188":152.0},"RAMP_TO_RAMP":{"18725":375.0,"100471":4537.0,"124633":5034.0,"26827":48.0,"46188":141.0},"AIR_TIME":{"18725":351.0,"100471":4208.0,"124633":3579.0,"26827":36.0,"46188":116.0},"UNIQUE_CARRIER":{"18725":"UA","100471":"5X","124633":"S5","26827":"ZK","46188":"WN"},"AIRLINE_ID":{"18725":19977.0,"100471":19917.0,"124633":20448.0,"26827":20358.0,"46188":19393.0},"UNIQUE_CARRIER_NAME":{"18725":"United Air Lines Inc.","100471":"United Parcel Service","124633":"Shuttle America Corp.","26827":"Great Lakes Airlines","46188":"Southwest Airlines Co."},"UNIQUE_CARRIER_ENTITY":{"18725":"10876","100471":"06910","124633":"06911","26827":"06932","46188":"06725"},"REGION":{"18725":"L","100471":"D","124633":"D","26827":"D","46188":"D"},"CARRIER":{"18725":"UA","100471":"5X","124633":"S5","26827":"ZK","46188":"WN"},"CARRIER_NAME":{"18725":"United Air Lines Inc.","100471":"United Parcel Service","124633":"Shuttle America Corp.","26827":"Great Lakes Airlines","46188":"Southwest Airlines Co."},"CARRIER_GROUP":{"18725":3,"100471":3,"124633":2,"26827":1,"46188":3},"CARRIER_GROUP_NEW":{"18725":3.0,"100471":3.0,"124633":2.0,"26827":6.0,"46188":3.0},"ORIGIN_AIRPORT_ID":{"18725":14843,"100471":10800,"124633":12339,"26827":10558,"46188":13198},"ORIGIN_AIRPORT_SEQ_ID":{"18725":1484304,"100471":1080003,"124633":1233904,"26827":1055803,"46188":1319801},"ORIGIN_CITY_MARKET_ID":{"18725":34819,"100471":32575,"124633":32337,"26827":30558,"46188":33198},"ORIGIN":{"18725":"SJU","100471":"BUR","124633":"IND","26827":"BFF","46188":"MCI"},"ORIGIN_CITY_NAME":{"18725":"San Juan, PR","100471":"Burbank, CA","124633":"Indianapolis, IN","26827":"Scottsbluff, NE","46188":"Kansas City, MO"},"ORIGIN_STATE_ABR":{"18725":"PR","100471":"CA","124633":"IN","26827":"NE","46188":"MO"},"ORIGIN_STATE_FIPS":{"18725":72.0,"100471":6.0,"124633":18.0,"26827":31.0,"46188":29.0},"ORIGIN_STATE_NM":{"18725":"Puerto Rico","100471":"California","124633":"Indiana","26827":"Nebraska","46188":"Missouri"},"ORIGIN_COUNTRY":{"18725":"US","100471":"US","124633":"US","26827":"US","46188":"US"},"ORIGIN_COUNTRY_NAME":{"18725":"United States","100471":"United States","124633":"United States","26827":"United States","46188":"United States"},"ORIGIN_WAC":{"18725":3,"100471":91,"124633":42,"26827":65,"46188":64},"DEST_AIRPORT_ID":{"18725":11988,"100471":14730,"124633":12953,"26827":12899,"46188":13871},"DEST_AIRPORT_SEQ_ID":{"18725":1198802,"100471":1473003,"124633":1295302,"26827":1289902,"46188":1387102},"DEST_CITY_MARKET_ID":{"18725":30966,"100471":33044,"124633":31703,"26827":32899,"46188":33316},"DEST":{"18725":"GRU","100471":"SDF","124633":"LGA","26827":"LBF","46188":"OMA"},"DEST_CITY_NAME":{"18725":"Sao Paulo, Brazil","100471":"Louisville, KY","124633":"New York, NY","26827":"North Platte, NE","46188":"Omaha, NE"},"DEST_STATE_ABR":{"18725":null,"100471":"KY","124633":"NY","26827":"NE","46188":"NE"},"DEST_STATE_FIPS":{"18725":null,"100471":21.0,"124633":36.0,"26827":31.0,"46188":31.0},"DEST_STATE_NM":{"18725":null,"100471":"Kentucky","124633":"New York","26827":"Nebraska","46188":"Nebraska"},"DEST_COUNTRY":{"18725":"BR","100471":"US","124633":"US","26827":"US","46188":"US"},"DEST_COUNTRY_NAME":{"18725":"Brazil","100471":"United States","124633":"United States","26827":"United States","46188":"United States"},"DEST_WAC":{"18725":316,"100471":52,"124633":22,"26827":65,"46188":65},"AIRCRAFT_GROUP":{"18725":6,"100471":6,"124633":6,"26827":4,"46188":6},"AIRCRAFT_TYPE":{"18725":627,"100471":691,"124633":677,"26827":461,"46188":612},"AIRCRAFT_CONFIG":{"18725":1,"100471":2,"124633":1,"26827":1,"46188":1},"YEAR":{"18725":2015,"100471":2015,"124633":2015,"26827":2015,"46188":2015},"QUARTER":{"18725":1,"100471":2,"124633":1,"26827":1,"46188":2},"MONTH":{"18725":2,"100471":4,"124633":2,"26827":3,"46188":4},"DISTANCE_GROUP":{"18725":7,"100471":4,"124633":2,"26827":1,"46188":1},"CLASS":{"18725":"F","100471":"G","124633":"F","26827":"F","46188":"F"},"DATA_SOURCE":{"18725":"IU","100471":"DU","124633":"DU","26827":"DU","46188":"DU"},"Unnamed: 50":{"18725":null,"100471":null,"124633":null,"26827":null,"46188":null}}'

# Reading Excel

In [10]:
accidentes_2009 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',skiprows=7,skipfooter=1,parse_cols='A:K')
accidentes_2009

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
0,ARGANZUELA,389,54,126,75,9.0,43,9,4.0,5,8
1,BARAJAS,89,6,53,21,NaN,12,2,1.0,2,2
2,CARABANCHEL,375,44,171,137,8.0,36,13,6.0,9,8
3,CENTRO,514,55,171,143,NaN,61,12,3.0,10,12
4,CHAMARTIN,494,70,133,92,10.0,72,22,2.0,6,7
5,CHAMBERI,414,35,87,87,3.0,51,12,4.0,4,5
6,CIUDAD LINEAL,398,64,124,101,3.0,57,17,5.0,4,4
7,FUENCARRAL-EL PARDO,321,47,151,78,11.0,34,16,7.0,2,8
8,HORTALEZA,215,16,109,58,3.0,29,13,7.0,4,4
9,LATINA,298,40,134,85,7.0,24,10,2.0,9,11
10,MONCLOA-ARAVACA,340,57,210,71,11.0,48,8,7.0,1,13
11,MORATALAZ,151,26,59,40,NaN,23,3,2.0,3,4
12,PUENTE DE VALLECAS,367,54,196,122,8.0,22,14,2.0,5,11
13,RETIRO,369,59,74,51,4.0,48,10,8.0,6,6
14,SALAMANCA,535,56,122,104,3.0,107,31,NaN,5,2
15,SAN BLAS,301,29,88,66,3.0,20,10,3.0,2,5
16,TETUAN,338,23,115,101,1.0,42,15,5.0,7,8
17,USERA,214,24,96,53,1.0,13,2,1.0,4,3
18,VICALVARO,86,6,39,15,6.0,9,4,3.0,2,2
19,VILLA DE VALLECAS,142,6,67,36,3.0,8,4,1.0,2,3
20,VILLAVERDE,148,19,65,46,4.0,9,4,3.0,1,8

In [15]:
accidentes_2010 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2010')
accidentes_2010

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS
0,ARGANZUELA,403,48,103,75,7,26,15.0,2.0,5.0,6.0
1,BARAJAS,62,5,34,22,1,11,NaN,NaN,NaN,NaN
2,CARABANCHEL,357,35,133,114,7,22,14.0,6.0,7.0,1.0
3,CENTRO,546,43,142,169,2,60,14.0,9.0,13.0,9.0
4,CHAMARTIN,460,67,128,85,11,77,16.0,1.0,8.0,5.0
5,CHAMBERI,361,34,86,103,1,66,14.0,5.0,2.0,4.0
6,CIUDAD LINEAL,404,79,120,90,8,39,12.0,6.0,7.0,2.0
7,FUENCARRAL-EL PARDO,294,49,165,72,10,26,9.0,6.0,3.0,2.0
8,HORTALEZA,183,15,68,44,4,11,8.0,4.0,3.0,3.0
9,LATINA,273,37,93,94,6,24,4.0,7.0,10.0,4.0
10,MONCLOA-ARAVACA,350,47,177,75,10,45,9.0,6.0,9.0,11.0
11,MORATALAZ,127,21,58,33,6,13,5.0,2.0,2.0,1.0
12,PUENTE DE VALLECAS,324,44,157,107,7,20,9.0,3.0,8.0,7.0
13,RETIRO,349,55,33,57,2,45,12.0,7.0,7.0,5.0
14,SALAMANCA,506,44,131,89,6,89,19.0,1.0,9.0,6.0
15,SAN BLAS,274,27,62,66,2,22,6.0,2.0,5.0,2.0
16,TETUAN,331,25,87,89,3,47,13.0,6.0,4.0,3.0
17,USERA,178,36,78,78,4,14,2.0,4.0,NaN,4.0
18,VICALVARO,65,4,60,22,3,16,NaN,1.0,1.0,5.0
19,VILLA DE VALLECAS,124,9,63,32,8,9,3.0,1.0,NaN,3.0
20,VILLAVERDE,147,21,58,54,2,9,4.0,2.0,2.0,1.0

In [16]:
accidentes_2009 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2009')
accidentes_2009['YEAR']= '2009'

accidentes_2010 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2010')
accidentes_2010['YEAR']= '2010'

accidentes_2011 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2011')
accidentes_2011['YEAR']= '2011'

accidentes_totales = pd.concat([accidentes_2009, accidentes_2010, accidentes_2011], ignore_index=True)
accidentes_totales.sort_values(by=['DISTRITO_ACCIDENTE'])
#accidentes_totales[['DISTRITO_ACCIDENTE', 'YEAR', ]]

,DISTRITO_ACCIDENTE,COLISIÓN DOBLE,COLISIÓN MÚLTIPLE,CHOQUE CON OBJETO FIJO,ATROPELLO,VUELCO,CAÍDA MOTOCICLETA,CAÍDA CICLOMOTOR,CAÍDA BICICLETA,CAÍDA VIAJERO BUS,OTRAS CAUSAS,YEAR
0,ARGANZUELA,389,54,126,75,9.0,43,9.0,4.0,5.0,8.0,2009
21,ARGANZUELA,403,48,103,75,7.0,26,15.0,2.0,5.0,6.0,2010
42,ARGANZUELA,373,48,102,61,3.0,45,14.0,5.0,3.0,NaN,2011
1,BARAJAS,89,6,53,21,NaN,12,2.0,1.0,2.0,2.0,2009
22,BARAJAS,62,5,34,22,1.0,11,NaN,NaN,NaN,NaN,2010
43,BARAJAS,78,3,44,30,3.0,9,3.0,NaN,1.0,NaN,2011
2,CARABANCHEL,375,44,171,137,8.0,36,13.0,6.0,9.0,8.0,2009
23,CARABANCHEL,357,35,133,114,7.0,22,14.0,6.0,7.0,1.0,2010
44,CARABANCHEL,381,48,125,103,3.0,36,8.0,10.0,8.0,4.0,2011
3,CENTRO,514,55,171,143,NaN,61,12.0,3.0,10.0,12.0,2009
24,CENTRO,546,43,142,169,2.0,60,14.0,9.0,13.0,9.0,2010
45,CENTRO,528,48,173,149,4.0,77,13.0,6.0,3.0,6.0,2011
4,CHAMARTIN,494,70,133,92,10.0,72,22.0,2.0,6.0,7.0,2009
25,CHAMARTIN,460,67,128,85,11.0,77,16.0,1.0,8.0,5.0,2010
46,CHAMARTIN,514,72,122,73,5.0,76,8.0,7.0,5.0,6.0,2011
26,CHAMBERI,361,34,86,103,1.0,66,14.0,5.0,2.0,4.0,2010
47,CHAMBERI,414,24,72,102,NaN,68,15.0,6.0,7.0,4.0,2011
5,CHAMBERI,414,35,87,87,3.0,51,12.0,4.0,4.0,5.0,2009
48,CIUDAD LINEAL,371,68,150,112,8.0,54,11.0,5.0,6.0,2.0,2011
6,CIUDAD LINEAL,398,64,124,101,3.0,57,17.0,5.0,4.0,4.0,2009
27,CIUDAD LINEAL,404,79,120,90,8.0,39,12.0,6.0,7.0,2.0,2010
49,FUENCARRAL-EL PARDO,312,42,128,89,12.0,30,9.0,16.0,1.0,4.0,2011
7,FUENCARRAL-EL PARDO,321,47,151,78,11.0,34,16.0,7.0,2.0,8.0,2009
28,FUENCARRAL-EL PARDO,294,49,165,72,10.0,26,9.0,6.0,3.0,2.0,2010
50,HORTALEZA,189,18,91,43,3.0,28,12.0,3.0,2.0,2.0,2011
8,HORTALEZA,215,16,109,58,3.0,29,13.0,7.0,4.0,4.0,2009
29,HORTALEZA,183,15,68,44,4.0,11,8.0,4.0,3.0,3.0,2010
51,LATINA,285,35,114,88,1.0,20,8.0,4.0,9.0,3.0,2011
9,LATINA,298,40,134,85,7.0,24,10.0,2.0,9.0,11.0,2009
30,LATINA,273,37,93,94,6.0,24,4.0,7.0,10.0,4.0,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
32,MORATALAZ,127,21,58,33,6.0,13,5.0,2.0,2.0,1.0,2010
53,MORATALAZ,137,16,52,34,5.0,12,6.0,2.0,2.0,3.0,2011
11,MORATALAZ,151,26,59,40,NaN,23,3.0,2.0,3.0,4.0,2009
33,PUENTE DE VALLECAS,324,44,157,107,7.0,20,9.0,3.0,8.0,7.0,2010
54,PUENTE DE VALLECAS,344,54,182,116,4.0,30,14.0,3.0,1.0,4.0,2011
12,PUENTE DE VALLECAS,367,54,196,122,8.0,22,14.0,2.0,5.0,11.0,2009
34,RETIRO,349,55,33,57,2.0,45,12.0,7.0,7.0,5.0,2010
55,RETIRO,367,73,71,68,3.0,50,9.0,6.0,6.0,5.0,2011
13,RETIRO,369,59,74,51,4.0,48,10.0,8.0,6.0,6.0,2009
35,SALAMANCA,506,44,131,89,6.0,89,19.0,1.0,9.0,6.0,2010
56,SALAMANCA,528,69,132,97,1.0,82,17.0,5.0,3.0,6.0,2011
14,SALAMANCA,535,56,122,104,3.0,107,31.0,NaN,5.0,2.0,2009
57,SAN BLAS,285,25,74,71,2.0,32,8.0,5.0,2.0,1.0,2011
15,SAN BLAS,301,29,88,66,3.0,20,10.0,3.0,2.0,5.0,2009
36,SAN BLAS,274,27,62,66,2.0,22,6.0,2.0,5.0,2.0,2010
37,TETUAN,331,25,87,89,3.0,47,13.0,6.0,4.0,3.0,2010
58,TETUAN,321,23,76,87,NaN,60,15.0,4.0,2.0,1.0,2011
16,TETUAN,338,23,115,101,1.0,42,15.0,5.0,7.0,8.0,2009
17,USERA,214,24,96,53,1.0,13,2.0,1.0,4.0,3.0,2009
38,USERA,178,36,78,78,4.0,14,2.0,4.0,NaN,4.0,2010
59,USERA,179,25,67,75,3.0,14,1.0,NaN,4.0,1.0,2011
18,VICALVARO,86,6,39,15,6.0,9,4.0,3.0,2.0,2.0,2009
39,VICALVARO,65,4,60,22,3.0,16,NaN,1.0,1.0,5.0,2010
60,VICALVARO,73,9,43,22,2.0,10,1.0,1.0,2.0,4.0,2011
61,VILLA DE VALLECAS,129,8,44,34,4.0,11,3.0,2.0,1.0,1.0,2011
19,VILLA DE VALLECAS,142,6,67,36,3.0,8,4.0,1.0,2.0,3.0,2009
40,VILLA DE VALLECAS,124,9,63,32,8.0,9,3.0,1.0,NaN,3.0,2010
20,VILLAVERDE,148,19,65,46,4.0,9,4.0,3.0,1.0,8.0,2009
41,VILLAVERDE,147,21,58,54,2.0,9,4.0,2.0,2.0,1.0,2010
62,VILLAVERDE,140,10,75,46,1.0,5,5.0,1.0,3.0,2.0,2011

In [17]:
periodo = [2009,2010,2011,2012,2013,2014,2015]

pd

for i in periodo


accidentes_2009 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2009')
accidentes_2009['YEAR']= '2009'

accidentes_2010 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2010')
accidentes_2010['YEAR']= '2010'

accidentes_2011 = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname='2011')
accidentes_2011['YEAR']= '2011'

accidentes_totales = pd.concat([accidentes_2009, accidentes_2010, accidentes_2011], ignore_index=True)
accidentes_totales.sort_values(by=['DISTRITO_ACCIDENTE'])

SyntaxError: invalid syntax (<ipython-input-17-b0ffa82f08aa>, line 5)

In [ ]:
sheets= pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=7,skipfooter=1,parse_cols='A:K',sheetname=None)
sheets.keys()
result = []
for name in  sheets.keys():
    year = int(name)
    skiprows = 4 if year==2013 else 7
    this_sheet = pd.read_excel('/home/dsc/Downloads/01_ ACCIDENTES POR TIPO EN  DISTRITOS.xls',
              skiprows=skiprows,skipfooter=1,parse_cols='A:K',sheetname=name)
   
    this_sheet['YEAR']= year
    result.append(this_sheet)
    
whole_df = pd.concat(result)
whole_df.sample(4)

In [ ]:
type(accidentes_2009)

#### Exercise

Consolidate the excel into one DataFrame: you will need to create a 'YEAR' column. Think how you can iterate through all the DataFrames. Think also where you can take the value of 'YEAR' from.

# Reading mysql database